name: CI

on: [push]

jobs:
  dast_scan:
    name: Run DUST scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Pull PyGoat Docker Image
        run: docker pull pygoat/pygoat:latest

      - name: Run PyGoat Container
        run: docker run --rm -d -p 8000:8000 pygoat/pygoat:latest

      - name: Wait for PyGoat to start
        run: |
          echo "Waiting for PyGoat to start..."
          sleep 15

      - name: Set up ZAP
        run: |
          docker pull owasp/zap2docker-stable

      - name: Run ZAP Security Scanner
        run: |
          docker run -t -u zap -v $(pwd):/zap/wrk/:rw -config api.disablekey=true owasp/zap2docker-stable zap-baseline.py -t http://localhost:8000 -r zap_report.html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
